aliases:
  # Templates
  - &SmartSyncExplorerSwift
    https://github.com/forcedotcom/SalesforceMobileSDK-Templates/SmartSyncExplorerSwift\#dev      
  - &SmartSyncExplorerReactNative
    https://github.com/forcedotcom/SalesforceMobileSDK-Templates/SmartSyncExplorerReactNative\#dev

  - &setup
    name: Setup
    command: ./install.sh
    when: always
  
  - &all-jobs
    - test-android:
        name: "Java"
        app_type: "native"
    - test-android:
        name: "Kotlin"
        app_type: "native_kotlin"
    - test-android:
        name: "Hybrid Local (Android)"
        app_type: "hybrid_local"
    - test-android:
        name: "Hybrid Remote (Android)"
        app_type: "hybrid_remote"
    - test-android:
        name: "React Native (Android)"
        app_type: "react_native"
        e: android-react-native
    - test-android:
        name: "SmartSyncExplorerReactNative (Android)"
        app_type: *SmartSyncExplorerReactNative
        template: true 
        e: android-react-native
    # - test-ios:
    #     name: "iOS 13"
    #     e:
    #       name: mac
    #       xcode: "11.0.0"
    #     device: "iPhone XR"
    #     ios_version: "13.0"    
    - test-ios:
        name: iOS 12
        e:
          name: mac
          xcode: "10.2.1"
        device: "iPhone XR"
        ios_version: "12.2"
    - test-ios:
        name: iOS 11
        e: 
          name: mac
          xcode: "10.2.1"
        device: "iPhone X"
        ios_version: "11.4"

  - &all-jobs-sfdx
    - test-android:
        name: "Java SFDX"
        app_type: "native"
        sfdx: true
    - test-android:
        name: "Kotlin SFDX"
        app_type: "native_kotlin"
        sfdx: true
    - test-android:
        name: "Hybrid Local (Android) SFDX"
        app_type: "hybrid_local"
        sfdx: true
    - test-android:
        name: "Hybrid Remote (Android) SFDX"
        app_type: "hybrid_remote"
        sfdx: true
    - test-android:
        name: "React Native (Android) SFDX"
        app_type: "react_native"
        sfdx: true
        e: android-react-native
    - test-android:
        name: "SmartSyncExplorerReactNative (Android) SFDX"
        app_type: *SmartSyncExplorerReactNative
        template: true
        sfdx: true
        e: android-react-native
    # - test-ios:
    #     name: "iOS 13 SFDX"
    #     e:
    #       name: mac
    #       xcode: "11.0.0"
    #     device: "iPhone XR"
    #     ios_version: "13.0"
    #     sfdx: true
    - test-ios:
        name: "iOS 12 SFDX"
        e:
          name: mac
          xcode: "10.2.1"
        device: "iPhone XR"
        ios_version: "12.2"
        sfdx: true
    - test-ios:
        name: "iOS 11 SFDX"
        e:
          name: mac
          xcode: "10.2.1"
        device: "iPhone X"
        ios_version: "11.4"
        sfdx: true

executors:
  android:
    working_directory: ~/SalesforceMobileSDK-UITests
    docker:
      - image: circleci/android:api-29-node
    environment:
      - TERM: "dumb"
      - GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      - FASTLANE_SKIP_UPDATE_CHECK: true
  android-react-native:
    working_directory: ~/SalesforceMobileSDK-UITests
    docker:
      - image: circleci/android:api-29-node
    environment:
      - TERM: "dumb"
      - GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1-1024m -XX:+HeapDumpOnOutOfMemoryError"'
      - FASTLANE_SKIP_UPDATE_CHECK: true
  mac:
    parameters:
      xcode:
        type: string
        default: "11.0.0"
    working_directory: ~/SalesforceMobileSDK-UITests
    macos:
      xcode: << parameters.xcode >>
    shell: /bin/bash --login -eo pipefail
    environment:
      - FASTLANE_SKIP_UPDATE_CHECK: true
    

version: 2.1
jobs:
  test-android:
    executor: << parameters.e >>
    parameters:
      app_type: 
        type: string
        default: "native"
      template:
        type: boolean
        default: false
      sfdx:
        type: boolean
        default: false
      e:
        type: executor
        default: "android"
    steps:
      - checkout
      - run: 
          name: Update Git
          command:  |
            git --version
            sudo apt-get update
            sudo apt-get install \
              build-essential flex bison \
              libreadline6-dev zlib1g-dev \
              libssl-dev \
              libcurl4-gnutls-dev \
              libexpat1-dev \
              tcl tk \
              tcl-dev gettext \
              asciidoc \
              docbook2x
            wget https://www.kernel.org/pub/software/scm/git/git-2.13.0.tar.gz
            tar -xvzf git-2.13.0.tar.gz
            cd git-2.13.0
            sudo ./configure
            sudo make && sudo make install
      - run: *setup
      - run: 
          name: Authorize gcloud and set config defaults
          command:  |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project mobile-apps-firebase-test
      - when:
          condition: << parameters.sfdx >>
          steps:
            - run:
                name: Install SFDX
                command: |
                  sudo npm install -g sfdx-cli
                  sudo chown -R `whoami` $HOME/.config/
      - when:
          condition: << parameters.template >>
          steps:
            - run:
                name: Test Android Template Test
                command: cd .circleci && fastlane android template:<< parameters.app_type >> sfdx:"<< parameters.sfdx >>"
                when: always
      - unless:
          condition: << parameters.template >>
          steps:
            - run:
                name: Test << parameters.app_type >> Android
                command: cd .circleci && fastlane android type:<< parameters.app_type >> sfdx:"<< parameters.sfdx >>"
                when: always
      - run: 
          name: Copy test results data
          command: |
            mkdir -p firebase/results
            gsutil -m cp -r gs://test-lab-w87i9sz6q175u-kwp8ium6js0zw/UITest-<< parameters.app_type >>-${CIRCLE_BUILD_NUM} ./firebase/ || true

            count=0
            for result in $(find ./firebase/ -name 'test_result*'); do
              mv $result "./firebase/results/result${count}.xml" && (( count++ )) || true 
            done
          when: always
      - store_artifacts:
          path: firebase
          when: always
      - store_test_results:
          path: firebase/results
          when: always

  test-ios:
      executor: << parameters.e >>
      parameters:
        ios_version: 
            type: string
        device:
            type: string
        e:
            type: executor
        sfdx:
          type: boolean
          default: false
      steps:
        - checkout
        - run: *setup
        - when:
            condition: << parameters.sfdx >>
            steps:
              - run:
                  name: Install SFDX
                  command: npm install -g sfdx-cli
        - run:
            name: Test Native Objective-C App
            command: cd .circleci && fastlane ios type:native device:"<< parameters.device >>" ios:"<< parameters.ios_version >>" sfdx:"<< parameters.sfdx >>"
            when: always
        - run:
            name: Test Native Swift App
            command: xcrun swift -version && cd .circleci && fastlane ios type:native_swift device:"<< parameters.device >>" ios:"<< parameters.ios_version >>" sfdx:"<< parameters.sfdx >>"
            when: always
        - run:
            name: Test Hybrid Local App
            command: cd .circleci && fastlane ios type:hybrid_local device:"<< parameters.device >>" ios:"<< parameters.ios_version >>" sfdx:"<< parameters.sfdx >>"
            when: always
        - run:
            name: Test Hyrbid Remote App
            command: cd .circleci && fastlane ios type:hybrid_remote device:"<< parameters.device >>" ios:"<< parameters.ios_version >>" sfdx:"<< parameters.sfdx >>"
            when: always
        - run:
            name: Test React Native App
            command: cd .circleci && fastlane ios type:react_native device:"<< parameters.device >>" ios:"<< parameters.ios_version >>" sfdx:"<< parameters.sfdx >>"
            when: always
        - run:
            name: Test SmartSync Swift Template
            command: cd .circleci && fastlane ios template:https://github.com/forcedotcom/SalesforceMobileSDK-Templates/SmartSyncExplorerSwift\#dev device:"<< parameters.device >>" ios:"<< parameters.ios_version >>" sfdx:"<< parameters.sfdx >>"
            when: always
        - run:
            name: Test SmartSync React Native Template
            command: cd .circleci && fastlane ios template:https://github.com/forcedotcom/SalesforceMobileSDK-Templates/SmartSyncExplorerReactNative\#dev device:"<< parameters.device >>" ios:"<< parameters.ios_version >>" sfdx:"<< parameters.sfdx >>"
            when: always        
        - store_artifacts:
            path: test_output
        - store_test_results:
            path: test_output


workflows:
  pr:
    jobs:
      *all-jobs

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything on Saturday Afternoon
  build-all-apps:
    triggers:
      - schedule:
          cron: "30 19 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      *all-jobs

  build-all-apps-sfdx:
    triggers:
      - schedule:
          cron: "30 21 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      *all-jobs-sfdx